### ISSUE TITLE
Sleep RFM69 module

### ISSUE THREAD

**Issue by JohnOH** [jcw/jeelib#89]
There appears to be an opportunity to use rf12_sleep while there is something pending such that coming out of rf12_sleep has missed an interrupt.

**Comment by jcw** [comment]
Please help my mushy neurons out a bit: which of the 4 driver combinations is this about?
I.e. 12 / 69 x native / compat ...

**Comment by JohnOH** [comment]
Sorry, I forget there is anything else when I'm in the groove. RF12 compatibility.

**Comment by jcw** [comment]
Ok, clear. For placeholders, I suggest assigning yourself to such issues, so we'll both remember?

**Comment by JohnOH** [comment]
Long forgotten now.
