### ISSUE TITLE
[QUESTION] Will your libraries work on Arduino Uno interfaced with any other RF IC?

### ISSUE THREAD

**Issue by rahulraghu94** [jcw/jeelib#91]
....Or do I need the JeeNodes Board?

**Comment by jcw** [comment]
JeeLib drivers work with RFM12 and RFM69. It should work with any AVR-based Arduino if the pins are connected properly (but beware of 5V/3.3V voltage levels). Is that what you're asking?

**Comment by rahulraghu94** [comment]
Yes it is! 
Thanks you so much!
